baseURL = ""
relativeURLs = "True"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Portio"
# Main Menu
[[menu.main]]
name = "About me"
url = "#about"
weight = 1
[[menu.main]]
name = "Services"
url = "#service"
weight = 2
[[menu.main]]
name = "Projects"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "Clients"
url = "#client"
weight = 4
[[menu.main]]
name = "References"
url = "#testimonial"
weight = 5


[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Brussels, Belgium"
email = "ernest.song@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(32) 476 60 05 90"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/ernestsong/"
weight = 1
